### ISSUE TITLE
ivy.nce_loss

### ISSUE THREAD

**Issue by JoaoPicolo** [ivy-llc/ivy#14016]
**Why should this be implemented?**
This is a subtask of #1548, I wasn't able to find this function in any other framework.

**Links to native framework implementations**
- [TensorFlow](https://www.tensorflow.org/api_docs/python/tf/nn/nce_loss)

**Comment by AnnaTz** [comment]
Great suggestion! All nn related functions are eligible to be added to our api straight away. I have added it to the list.
