### ISSUE TITLE
set_backend 

### ISSUE THREAD

**Issue by CatB1t** [ivy-llc/ivy#1819]
Current implementation does not handle if ```set_backend()``` fails to import a module, this results in the global backend stack always set to empty after an exception. This breaks the expected behaviour of ```unset_backend``` function too.

for example:
```python
>>> ivy.set_backend('tensorflow')
>>> ivy.set_backend('numpy')
>>> ivy.set_backend('torch')
>>> ivy.backend
'torch'

>>> ivy.unset_backend()
>>> ivy.backend
'numpy'
```

if we try to do the same but we mistype one of the frameworks, ivy.backend_stack will always be empty after an exception.
```python
>>> ivy.set_backend('tensorflow')
>>> ivy.set_backend('numpy')
>>> ivy.set_backend('ttorch') # Typo in framework name
KeyError: 'ttorch'
>>> ivy.backend
'none'
```

I'm assuming the backend should not be cleared unless explicitly called using ```clear_backend_stack()```.

**Comment by MarShaikh** [comment]
Thanks for pointing this out @CatB1t, I just started a discussion with this topic [here](https://github.com/unifyai/ivy/discussions/1313#discussioncomment-3171198).

**Comment by Ishticode** [comment]
fixed in [this commit](https://github.com/unifyai/ivy/commit/6b77c2b3c47fa0e718358d3067caa1fd31760f8e). Thank you for raising the issue.
