### ISSUE TITLE
Graph Compiler renamed to Tracer

### ISSUE THREAD

**Issue by HaiderSultanArc** [ivy-llc/ivy#22838]
We are updating our `ivy.compile( )` function to `ivy.trace\_graph( )` function. 
This requires updating the Docs, Ivy Repo, Graph Compiler Repo, Demos, and other places to refer to Tracer rather than Graph Compiler!

Discord Discussion: https://discord.com/channels/799879767196958751/1088437511925272717/1144634211920248947

Updates Required:
- [x] #22839
- [x] #22855
- [x] #22933
- [ ] #26156
- [ ] Links and Assets
- [ ] Forums and Community

**Comment by Tribhuvan0** [comment]
Hi @HaiderSultanArc  I am a beginner and have read about the structure and design of ivy, so got a basic idea. Can I start working on it, and will you please help me out on this issue

**Comment by HaiderSultanArc** [comment]
> Hi @HaiderSultanArc I am a beginner and have read about the structure and design of ivy, so got a basic idea. Can I start working on it, and will you please help me out on this issue

@Tribhuvan0 This is an internal task. You can look for other tasks in our issues 😄. Thanks!

**Comment by Aryan8912** [comment]
I am working on this issue

**Comment by HaiderSultanArc** [comment]
@Aryan8912 this is an internal issue and task. You can pick some other task from our todo lists 😄

**Comment by anudeeps0306** [comment]
#26288

**Comment by HaiderSultanArc** [comment]
Hey @anudeeps0306 I don't know what you are trying to do 😅 this is an internal task. You can select some other task from "ToDo" label. I have to close your issue.
