### ISSUE TITLE
Invalid `default type` for environment variable

### ISSUE THREAD

**Issue by Sai-Suraj-27** [ivy-llc/ivy#27449]
The default value for `os.getenv` should be a  `string` or `None`, Otherwise it will be inconsistent with the [return type of `os.getenv`](https://docs.python.org/3/library/os.html#os.getenv).
This can cause errors.

If an environment variable is set, `os.getenv` will return its value as a string. If the environment variable is not set, `os.getenv` will return `None`, or the default value if one is provided. So, I guess the default value should be provided as `None`.

https://github.com/unifyai/ivy/blob/71b684745d403d290db4b5c5798cc5204ce9a22f/ivy_tests/conftest.py#L112

**Comment by vedpatwardhan** [comment]
Yep sounds good to me, feel free create a PR. Thanks @Sai-Suraj-27 😄
