### ISSUE TITLE
Fix Frontend Failing Test: torch - tensor.torch.Tensor.reshape_as

### ISSUE THREAD

**Issue by Aryan8912** [ivy-llc/ivy#28118]
To-do List: https://github.com/unifyai/ivy/issues/27498

**Comment by ivy-leaves** [comment]
Hello @contributor,

Great news! The test 'torch.Tensor.reshape_as' is now passing. We are closing this issue. Feel free to choose and work on another failing test.

Thank you for your contribution!

Best,
Ivy Team
