### ISSUE TITLE
[Bug]: Elementwise function cannot be applied or does not return the correct value to Python `float` when `ivy.set_array_mode(False)`

### ISSUE THREAD

**Issue by 34j** [ivy-llc/ivy#28839]
### Bug Explanation

Calculating `log(1)`:

```shell
python -c "import ivy; ivy.set_backend('torch'); ivy.set_array_mode(False); print(ivy.log(1))"
venv/lib/python3.11/site-packages/ivy/func_wrapper.py:440: UserWarning: In the case of Compositional function, operators might cause inconsistent behavior when array_mode is set to False
  warnings.warn(
tensor([])
```

```shell
python -c "import ivy; ivy.set_backend('numpy'); ivy.set_array_mode(False); print(ivy.log(1))"
(long output)
ivy.utils.exceptions.IvyBackendException: numpy: is_array: numpy: is_ivy_array: numpy: is_native_array: numpy: nested_argwhere: numpy: nested_argwhere: maximum recursion depth exceeded
```

These works:

```shell
python -c "import ivy; import numpy as np; ivy.set_backend('numpy'); ivy.set_array_mode(False); print(ivy.log(np.array(1)))"
0.0
```

```shell
python -c "import ivy; import torch; ivy.set_backend('torch'); ivy.set_array_mode(False); print(ivy.log(torch.tensor(1)))"
tensor(0.)
```

Perhaps this kind of usage is not expected, but I would just like to report it anyway.

### Steps to Reproduce Bug

```shell
python -c "import ivy; ivy.set_backend('numpy'); ivy.set_array_mode(False); print(ivy.log(1))"
python -c "import ivy; ivy.set_backend('torch'); ivy.set_array_mode(False); print(ivy.log(1))"
```

### Environment

Ubuntu 22.04

### Ivy Version

1.0.0.0

### Backend

- [X] NumPy
- [ ] TensorFlow
- [X] PyTorch
- [ ] JAX

### Device

CPU

**Comment by YushaArif99** [comment]
Hi @34j. Thanks alot for opening the issue. Upon some close inspection, it turns out the actual bug is originating from printing the result of `ivy.log(1)` which invokes the `__repr__` method of the `ivy.Array` class.  I have opened a [PR](https://github.com/ivy-llc/ivy/pull/28840) with the relevant fix, which should hopefully also resolve this issue you were experiencing. Let me know if this works or if the issue is still persisting on your end 😄

**Comment by 34j** [comment]
@YushaArif99 

I ran `pip install git+https://github.com/ivy-llc/ivy.git` and ran the command again, but unfortunately it does not seem to resolve the issue. I may be doing something wrong, so could you please run the two commands on your end to check this?

Also, as you said, the Numpy one seems to be related to `print`, but I think the PyTorch one is a different issue as the shape is already wrong.

```shell
$ python -c "import ivy; ivy.set_backend('torch'); ivy.set_array_mode(True); print(ivy.log(1).shape)"
ivy.Shape()
$ python -c "import ivy; ivy.set_backend('torch'); ivy.set_array_mode(False); print(ivy.log(1).shape)"
/home/z/ghq/github.com/mid-t-u-tokyo/torchsphharm/venv/lib/python3.11/site-packages/ivy/func_wrapper.py:440: UserWarning: In the case of Compositional function, operators might cause inconsistent behavior when array_mode is set to False
  warnings.warn(
torch.Size([0])
```

**Comment by 34j** [comment]
@YushaArif99 

I ran `pip install -U --force-reinstall git+https://github.com/ivy-llc/ivy.git` and ran the commands again, and the Numpy issue seems to be resolved.

```shelll
$ python -c "import ivy; ivy.set_backend('numpy'); ivy.set_array_mode(False); print(ivy.log(1))"
venv/lib/python3.11/site-packages/ivy/func_wrapper.py:440: UserWarning: In the case of Compositional function, operators might cause inconsistent behavior when array_mode is set to False
  warnings.warn(
ivy.array(0.)
```
However, the PyTorch one still persists.
I may be doing something wrong, so could you please run the two commands on your end to check this?

As you said, the Numpy one seems to be related to `print`, but I think the PyTorch one is a different issue as the shape is already wrong.

```shell
$ python -c "import ivy; ivy.set_backend('torch'); ivy.set_array_mode(True); print(ivy.log(1).shape)"
ivy.Shape()
$ python -c "import ivy; ivy.set_backend('torch'); ivy.set_array_mode(False); print(ivy.log(1).shape)"
venv/lib/python3.11/site-packages/ivy/func_wrapper.py:440: UserWarning: In the case of Compositional function, operators might cause inconsistent behavior when array_mode is set to False
  warnings.warn(
torch.Size([0])
```

**Comment by YushaArif99** [comment]
Hi @34j. Apologies for overlooking the 2nd example, totally slipped under my radar 😅 

I have opened another [PR]() with the `torch` fix as well which should hopefully resolve this 2nd issue as well.

These are the outputs I am getting:

```python

- import ivy; ivy.set_backend('numpy'); ivy.set_array_mode(False); print(ivy.log(1))
>>> 0.0

- import ivy; ivy.set_backend('numpy'); ivy.set_array_mode(True); print(ivy.log(1))
>>> ivy.array(0.)

- import ivy; ivy.set_backend('torch'); ivy.set_array_mode(False); print(ivy.log(1))
>>> tensor(0.)

- import ivy; ivy.set_backend('torch'); ivy.set_array_mode(True); print(ivy.log(1))
>>> ivy.array(0.)

```
